### ISSUE TITLE
邮件被退回

### ISSUE THREAD

**Issue by zscmmm** [Jinnrry/PMail#117]
**请说明问题 / Describe the bug**
我能给 QQ 邮箱发信息, 但是QQ 邮箱不能给 pmail 发送, 说域名不存在

**如何复现 / To Reproduce**
我采用 docker 搭建的,  测试过 163 邮箱,也不行

**你预期的行为 / Expected behavior**
希望能够正常的发送和回复消息

**贴上你的配置文件 / Program configuration file contents**

```
services:
    jinnrry:
        container_name: pmail
        image: 'ghcr.io/jinnrry/pmail:latest'
        volumes:
            - './config:/work/config'
        ports:
            - '465:465' 
            - '8681:443'
            - '8680:80'
            - '25:25'
```

</details>

**日志信息 / Log**
<details>
  <summary>log</summary>

```
⚡ sudo docker logs  pmail                                           
[info][2024-05-04 18:17:18][/work/main.go:81]*******************************************************************
[info][2024-05-04 18:17:18][/work/main.go:82]***        Server Start Success 

[info][2024-05-04 18:17:18][/work/main.go:83]***        Server Version: v2.4.7 

[info][2024-05-04 18:17:18][/work/main.go:84]***        Git Commit Hash: bd26a3904918d425f7619c4e7e1a1066bcb7c53b 
[info][2024-05-04 18:17:18][/work/main.go:85]***        Build Date: 2024-04-30 14:52:57 
[info][2024-05-04 18:17:18][/work/main.go:86]***        Build GoLang Version: go version go1.22.2 linux/amd64 
[info][2024-05-04 18:17:18][/work/main.go:87]*******************************************************************
[info][2024-05-04 18:17:18][/work/hooks/base.go:179][telegram_push] Plugin Load
[telegram_push] Plugin Start! PID:11[info][2024-05-04 18:17:19][/work/hooks/base.go:211][telegram_push] Plugin Load Success!
[info][2024-05-04 18:17:19][/work/hooks/base.go:179][web_push] Plugin Load
[web_push] Plugin Start! PID:16[info][2024-05-04 18:17:20][/work/hooks/base.go:211][web_push] Plugin Load Success!
[info][2024-05-04 18:17:20][/work/hooks/base.go:179][wechat_push] Plugin Load
panic: open ../../config/config.json: no such file or directory

goroutine 1 [running]:
main.NewWechatPushHook()
        /work/hooks/wechat_push/wechat_push.go:136 +0x27f
main.main()
        /work/hooks/wechat_push/wechat_push.go:186 +0x13
[wechat_push] Plugin Start! PID:22[error][2024-05-04 18:17:20][/work/hooks/base.go:195][wechat_push] Plugin Stop. Error:<nil> Stat:exit status 2
[error][2024-05-04 18:17:25][/work/hooks/base.go:206][wechat_push] Start Fail!
[warning][2024-05-04 18:17:25][/work/res_init/init.go:52]Config File Info:  {"logLevel":"","domain":"zsccy.top","domains":["zsccy.top"],"webDomain":"pmail.zsccy.top","dkimPrivateKeyPath":"config/dkim/dkim.priv","sslType":"1","SSLPrivateKeyPath":"./config/ssl/private.key","SSLPublicKeyPath":"./config/ssl/public.crt","dbDSN":"./config/pmail.db","dbType":"sqlite","httpsEnabled":2,"spamFilterLevel":0,"httpPort":0,"httpsPort":0,"weChatPushAppId":"","weChatPushSecret":"","weChatPushTemplateId":"","weChatPushUserId":"","tgBotToken":"","tgChatId":"","isInit":true,"webPushUrl":"","webPushToken":""}
[info][2024-05-04 18:17:25][/work/smtp_server/smtp.go:146]Starting Smtp With SSL Server Port: :465
[info][2024-05-04 18:17:25][/work/smtp_server/smtp.go:174]Starting Smtp Server Port: :25
[info][2024-05-04 18:17:25][/work/pop3_server/pop3server.go:27]POP3 With TLS Server Start On Port :995
[info][2024-05-04 18:17:25][/work/http_server/http_server.go:68]HttpServer Start On Port :80
[info][2024-05-04 18:17:25][/work/pop3_server/pop3server.go:46]POP3 Server Start On Port :110
[info][2024-05-04 18:19:24][ac1b000266360bac076e00011bf46db0][/work/controllers/email/send.go:57]发送邮件

```

</details>

**Comment by zscmmm** [comment]
已解决, 那个MX 解析要填写@
