### ISSUE TITLE
2.7.3启动报错

### ISSUE THREAD

**Issue by Fantecy** [Jinnrry/PMail#213]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

2.7.3

### 描述

[info][2024-09-28 23:14:33][/work/main.go:81]*******************************************************************
[info][2024-09-28 23:14:33][/work/main.go:82]***	Server Start Success 

[info][2024-09-28 23:14:33][/work/main.go:83]***	Server Version: v2.7.3 

[info][2024-09-28 23:14:33][/work/main.go:84]***	Git Commit Hash: b86c2582b5525e131ef36a9161c2d7f861013bc5 
[info][2024-09-28 23:14:33][/work/main.go:85]***	Build Date: 2024-09-28 11:32:58 
[info][2024-09-28 23:14:33][/work/main.go:86]***	Build GoLang Version: go version go1.23.1 linux/amd64 
[info][2024-09-28 23:14:33][/work/main.go:87]*******************************************************************
[info][2024-09-28 23:14:33][/work/services/setup/ssl/ssl.go:287]SSL certificate remaining time is only 20 days, renew SSL certificate.
[info][2024-09-28 23:14:33][/work/services/setup/ssl/ssl.go:287]SSL certificate remaining time is only 20 days, renew SSL certificate.
2024/09/28 23:14:34 [INFO] acme: Trying to resolve account by key
2024/09/28 23:14:35 [INFO] [pmail.fantecy.cn, smtp.fantecy.cn, pop.fantecy.cn] acme: Obtaining bundled SAN certificate
[info][2024-09-28 23:14:35][/work/services/setup/ssl/ssl.go:116]wait ssl renew
2024/09/28 23:14:35 [INFO] acme: Trying to resolve account by key
[info][2024-09-28 23:14:36][/work/services/setup/ssl/ssl.go:116]wait ssl renew
2024/09/28 23:14:36 [INFO] [pmail.fantecy.cn, smtp.fantecy.cn, pop.fantecy.cn] acme: Obtaining bundled SAN certificate
2024/09/28 23:14:37 [INFO] [pmail.fantecy.cn] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/409375952687
2024/09/28 23:14:37 [INFO] [pop.fantecy.cn] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/409375952697
2024/09/28 23:14:37 [INFO] [smtp.fantecy.cn] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/409375952707
2024/09/28 23:14:37 [INFO] [pmail.fantecy.cn] acme: Could not find solver for: tls-alpn-01
2024/09/28 23:14:37 [INFO] [pmail.fantecy.cn] acme: Could not find solver for: http-01
2024/09/28 23:14:37 [INFO] [pmail.fantecy.cn] acme: Could not find solver for: dns-01
2024/09/28 23:14:37 [INFO] [smtp.fantecy.cn] acme: Could not find solver for: tls-alpn-01
2024/09/28 23:14:37 [INFO] [smtp.fantecy.cn] acme: Could not find solver for: http-01
2024/09/28 23:14:37 [INFO] [smtp.fantecy.cn] acme: Could not find solver for: dns-01
2024/09/28 23:14:37 [INFO] [pop.fantecy.cn] acme: Could not find solver for: tls-alpn-01
2024/09/28 23:14:37 [INFO] [pop.fantecy.cn] acme: Could not find solver for: http-01
2024/09/28 23:14:37 [INFO] [pop.fantecy.cn] acme: Could not find solver for: dns-01
2024/09/28 23:14:38 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/409375952687
2024/09/28 23:14:38 [INFO] [pmail.fantecy.cn] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/409375952687
2024/09/28 23:14:38 [INFO] [pop.fantecy.cn] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/409375952697
2024/09/28 23:14:38 [INFO] [smtp.fantecy.cn] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/409375952707
2024/09/28 23:14:38 [INFO] [pmail.fantecy.cn] acme: Could not find solver for: tls-alpn-01
2024/09/28 23:14:38 [INFO] [pmail.fantecy.cn] acme: Could not find solver for: http-01
2024/09/28 23:14:38 [INFO] [pmail.fantecy.cn] acme: Could not find solver for: dns-01
2024/09/28 23:14:38 [INFO] [smtp.fantecy.cn] acme: Could not find solver for: tls-alpn-01
2024/09/28 23:14:38 [INFO] [smtp.fantecy.cn] acme: Could not find solver for: http-01
2024/09/28 23:14:38 [INFO] [smtp.fantecy.cn] acme: Could not find solver for: dns-01
2024/09/28 23:14:38 [INFO] [pop.fantecy.cn] acme: Could not find solver for: tls-alpn-01
2024/09/28 23:14:38 [INFO] [pop.fantecy.cn] acme: Could not find solver for: http-01
2024/09/28 23:14:38 [INFO] [pop.fantecy.cn] acme: Could not find solver for: dns-01
2024/09/28 23:14:38 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/409375952687
2024/09/28 23:14:39 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/409375952697
2024/09/28 23:14:39 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/409375952697
2024/09/28 23:14:39 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/409375952707
panic: error: one or more domains had a problem:
	[pmail.fantecy.cn] [pmail.fantecy.cn] acme: could not determine solvers
	[pop.fantecy.cn] [pop.fantecy.cn] acme: could not determine solvers
	[smtp.fantecy.cn] [smtp.fantecy.cn] acme: could not determine solvers
	

goroutine 1 [running]:
github.com/Jinnrry/pmail/services/setup/ssl.renewCertificate(0xc0001413e0, 0xc000002300)
	/work/services/setup/ssl/ssl.go:119 +0x608
github.com/Jinnrry/pmail/services/setup/ssl.GenSSL(0x1)
	/work/services/setup/ssl/ssl.go:248 +0xae
github.com/Jinnrry/pmail/services/setup/ssl.Update(0x0)
	/work/services/setup/ssl/ssl.go:289 +0x125
github.com/Jinnrry/pmail/res_init.Init({0xecc45c, 0x6})
	/work/res_init/init.go:33 +0x73
main.main()
	/work/main.go:93 +0x3da

### 重现方式

报错日志上述所示，启动时出现错误

### 服务端配置

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Jinnrry** [comment]
ssl挑战是用的http还是DNS记录认证？

**Comment by eternallyproud** [comment]
我这里也有这种报错，改了半天没成功。建议手动添加证书，证书可以用let's encrypt，或者找个免费分发证书的网站申请。

**Comment by Jinnrry** [comment]
> 我这里也有这种报错，改了半天没成功。建议手动添加证书，证书可以用let's encrypt，或者找个免费分发证书的网站申请。

sslType 设置成1就是手动指定证书

**Comment by Fantecy** [comment]
> ssl挑战是用的http还是DNS记录认证？

吃屎吧你，项目别写了
