### ISSUE TITLE
配置转发规则后panic

### ISSUE THREAD

**Issue by J3n5en** [Jinnrry/PMail#22]
```
[info][2023-09-08 23:50:08][/mnt/d/PMail/server/dto/parsemail/dkim.go:90]Valid signature for: gmail.com
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9d76c9]

goroutine 20 [running]:
main.(*logFormatter).Format(0x0?, 0xc00014ba40)
        /mnt/d/PMail/server/main.go:25 +0x169
github.com/sirupsen/logrus.(*Entry).write(0xc00014ba40)
        /home/jiangwei/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:289 +0xa5
github.com/sirupsen/logrus.(*Entry).log(0xc00014b9d0, 0x2, {0xc000341500, 0x6f0})
        /home/jiangwei/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x474
github.com/sirupsen/logrus.(*Entry).Log(0xc00014b9d0, 0x2, {0xc0004d37f0?, 0x2?, 0x2?})
        /home/jiangwei/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Logf(0xc00014b9d0, 0x2, {0xabdcc6?, 0xc00019d158?}, {0xc000077878?, 0xc000077860?, 0x462499?})
        /home/jiangwei/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0x85
github.com/sirupsen/logrus.(*Entry).Errorf(...)
        /home/jiangwei/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:378
pmail/utils/async.(*Async).HandleErrRecover(0xc000243d60, {0xa28f20?, 0x1334a00})
        /mnt/d/PMail/server/utils/async/async.go:68 +0x187
pmail/utils/async.(*Async).Process.func1.1()
        /mnt/d/PMail/server/utils/async/async.go:45 +0x3c
panic({0xa28f20, 0x1334a00})
        /usr/local/go/src/runtime/panic.go:884 +0x213
main.(*logFormatter).Format(0xc0003c3280?, 0xc00014b960)
        /mnt/d/PMail/server/main.go:25 +0x169
github.com/sirupsen/logrus.(*Entry).write(0xc00014b960)
        /home/jiangwei/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:289 +0xa5
github.com/sirupsen/logrus.(*Entry).log(0xc00014b8f0, 0x2, {0xc0003b18c0, 0x5c})
        /home/jiangwei/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x474
github.com/sirupsen/logrus.(*Entry).Log(0xc00014b8f0, 0x2, {0xc000077d08?, 0x1?, 0x1?})
        /home/jiangwei/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Logf(0xc00014b8f0, 0x2, {0xac0df3?, 0xc00017f800?}, {0xc000077f20?, 0x700?, 0x0?})
        /home/jiangwei/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0x85
github.com/sirupsen/logrus.(*Entry).Errorf(...)
        /home/jiangwei/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:378
pmail/utils/send.Forward.func1({0xa59620?, 0x9b4f67?})
        /mnt/d/PMail/server/utils/send/send.go:72 +0x39f
pmail/utils/async.(*Async).WaitProcess.func1({0x0?, 0x0?})
        /mnt/d/PMail/server/utils/async/async.go:37 +0x69
pmail/utils/async.(*Async).Process.func1()
        /mnt/d/PMail/server/utils/async/async.go:48 +0x67
created by pmail/utils/async.(*Async).Process
        /mnt/d/PMail/server/utils/async/async.go:42 +0xb5
```
配置的规则是：收件人地址  -   包含 - xxx 转发到  xxx@gmail.com

删掉规则后，发送相同邮件能进信箱

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.2.2

应该修复了
