### ISSUE TITLE
It ignores the "httpPort:" in config.json

### ISSUE THREAD

**Issue by zigomi** [Jinnrry/PMail#36]
I want to run it on any port other than the 80th - I don't want to use `sudo`

```
./build
```

then

```
vim output/config/config.json 
    "httpPort": 80 ===> "httpPort": 8080,
```

then

```
./output/pmail_linux_amd64
```

error:

```
panic: listen tcp :80: bind: permission denied
    goroutine 21 [running]:
    pmail/http_server.SetupStart()
            /<...>/PMail/server/http_server/setup_server.go:41 +0x298
    created by pmail/res_init.Init in goroutine 1
            /<...>/PMail/server/res_init/init.go:23 +0x57

```

**Comment by Jinnrry** [comment]
Could you show the complete contents of the configuration file?

**Comment by zigomi** [comment]
```
{
  "logLevel": "info",
  "domain": "domain.com",
  "webDomain": "mail.domain.com",
  "dkimPrivateKeyPath": "config/dkim/dkim.priv",
  "sslType": "0",
  "SSLPrivateKeyPath": "config/ssl/private.key",
  "SSLPublicKeyPath": "config/ssl/public.crt",
  "dbDSN": "./config/pmail.db",
  "dbType": "sqlite",
  "spamFilterLevel": 2,
  "httpPort": 8080,
  "httpsPort": 443,
  "weChatPushAppId": "",
  "weChatPushSecret": "",
  "weChatPushTemplateId": "",
  "weChatPushUserId": "",
  "tgChatId": "",
  "tgBotToken": "",
  "isInit": true,
  "httpsEnabled": 1
}                      
```

**Comment by Jinnrry** [comment]
Your program doesn't seem to be loading this configuration file.

Please check if your programme has other configuration files loaded.

**Comment by zigomi** [comment]
Ahh, now I should disable `443` port, right?

**Comment by Jinnrry** [comment]
Re-pull the master branch code and run it again. Show me the console output.

**Comment by zigomi** [comment]
```
% ./pmail_linux_amd64

[info][2023-11-02 09:25:42][tmp/PMail/server/main.go:76]***************************************************
[info][2023-11-02 09:25:42][tmp/PMail/server/main.go:77]***  Server Start Success Version:2.2.7

[info][2023-11-02 09:25:42][tmp/PMail/server/main.go:78]***  Git Commit Hash: 875228b886e52f31a4c0e76938680534ab9f7f0a 
[info][2023-11-02 09:25:42][tmp/PMail/server/main.go:79]***  Build TimeStamp: 2023-11-02 09:23:30 
[info][2023-11-02 09:25:42][tmp/PMail/server/main.go:80]***  Build GoLang Version: go version go1.21.3 linux/amd64 
[info][2023-11-02 09:25:42][tmp/PMail/server/main.go:81]***************************************************
[info][2023-11-02 09:25:42][tmp/PMail/server/db/init.go:73]Create Table: CREATE table email
(

<.............>

[info][2023-11-02 09:25:42][tmp/PMail/server/db/init.go:73]Create Table: CREATE TABLE user_auth
(
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id       int ,
    email_account varchar(30)
);

CREATE UNIQUE INDEX udx_uid_ename on user_auth ( user_id, email_account);
CREATE UNIQUE INDEX udx_ename_uid on user_auth ( email_account,user_id );
[info][2023-11-02 09:25:42][tmp/PMail/server/db/init.go:80]Init Table: 

[warning][2023-11-02 09:25:42][tmp/PMail/server/res_init/init.go:45]Config File Info:  {"logLevel":"info","domain":"domain.com","webDomain":"mail.domain.com","dkimPrivateKeyPath":"config/dkim/dkim.priv","sslType":"0","SSLPrivateKeyPath":"config/ssl/private.key","SSLPublicKeyPath":"config/ssl/public.crt","dbDSN":"./config/pmail.db","dbType":"sqlite","httpsEnabled":1,"spamFilterLevel":2,"httpPort":8080,"httpsPort":443,"weChatPushAppId":"","weChatPushSecret":"","weChatPushTemplateId":"","weChatPushUserId":"","tgBotToken":"","tgChatId":"","isInit":true}

[info][2023-11-02 09:25:42][tmp/PMail/server/smtp_server/smtp.go:70]Starting server at :25
[info][2023-11-02 09:25:42][tmp/PMail/server/http_server/https_server.go:76]Https Server Start On Port :443
[fatal][2023-11-02 09:25:42][tmp/PMail/server/smtp_server/smtp.go:72]listen tcp :25: bind: permission denied
```

**Comment by zigomi** [comment]
`sudo` must be used, right? With `sudo` it works.

**Comment by Jinnrry** [comment]
The program needs to receive mail through the smtp service. Smtp protocol runs on port 25, so port 25 must be used. Root privileges are required by the Linux system.

https://www.staldal.nu/tech/2007/10/31/why-can-only-root-listen-to-ports-below-1024/

**Comment by Jinnrry** [comment]
If you need to reconfigure, delete the config directory.

**Comment by zigomi** [comment]
Thx
