### ISSUE TITLE
[紧急求助] Pmail 初始化的时候怎么更改启动端口。

### ISSUE THREAD

**Issue by is52hertz** [Jinnrry/PMail#84]
# 系统信息
Ubuntu 20.04.6 LTS (Focal Fossa) x86_64(Py3.7.9)
2h4g
安装: bt面板(nginx, php8.2, mysql)

# 执行过程
> 无关目录均用 xxx 代替。
```bash
cd /xxx/xxx/
mkdir pmail
cd pmail
wget https://github.com/Jinnrry/PMail/releases/download/v2.3.8/pmail_linux_amd64
# 成功下载 pmail_linux_amd64 文件
chmod +x pmail_linux_amd64
./pmail_linux_amd64
```
> 报错
```
root@ser756xxx:/xxx/xxx/pmail# ./pmail_linux_amd64
[info][2024-02-19 20:26:09][/home/runner/work/PMail/PMail/server/main.go:76]***************************************************
[info][2024-02-19 20:26:09][/home/runner/work/PMail/PMail/server/main.go:77]*** Server Start Success Version:2.3.8

[info][2024-02-19 20:26:09][/home/runner/work/PMail/PMail/server/main.go:78]*** Git Commit Hash: 483bfa14c18396a5751a01838f19fccb6b7f8db8 
[info][2024-02-19 20:26:09][/home/runner/work/PMail/PMail/server/main.go:79]*** Build TimeStamp: 2024-02-18 19:43:28 
[info][2024-02-19 20:26:09][/home/runner/work/PMail/PMail/server/main.go:80]*** Build GoLang Version: go version go1.21.7 linux/amd64 
[info][2024-02-19 20:26:09][/home/runner/work/PMail/PMail/server/main.go:81]***************************************************
[info][2024-02-19 20:26:09][/home/runner/work/PMail/PMail/server/res_init/init.go:25]Please click http://127.0.0.1 to continue.

[info][2024-02-19 20:26:09][/home/runner/work/PMail/PMail/server/http_server/setup_server.go:33]HttpServer Start On Port :80
panic: listen tcp :80: bind: address already in use

goroutine 21 [running]:
pmail/http_server.SetupStart()
        /home/runner/work/PMail/PMail/server/http_server/setup_server.go:42 +0x310
created by pmail/res_init.Init in goroutine 1
        /home/runner/work/PMail/PMail/server/res_init/init.go:26 +0x57
```
## 所以
端口 **80** 被占用。
而这显然不能解除端口 **80** 的占用。
所以我想更改其 **pmail** 的端口。

### 求助

**Comment by Jinnrry** [comment]
不能，你可以在其他机器上初始化，完成后拷贝配置文件过去

**Comment by is52hertz** [comment]
> 不能，你可以在其他机器上初始化，完成后拷贝配置文件过去
```
[info][2024-02-19 21:03:17][/home/runner/work/PMail/PMail/server/res_init/init.go:25]Please click http://127.0.0.1 to continue.
```
咋更改访问地址啊
改了 `"httpPort": 80` 没效果

**Comment by is52hertz** [comment]
还是说要直接在其它机器上完成配置?

**Comment by Jinnrry** [comment]
在其他机器上完成配置，或者你照着readme里面的配置文件demo，手写一个配置文件也行。初始化过程也只是生成配置文件而已

**Comment by Jinnrry** [comment]
最新版本已经支持启动参数指定端口。不过必须在80端口添加转发，保证80端口的`/.well-known/`路由指向PMail，否则将导致SSL证书获取失败

**Comment by eternallyproud** [comment]
借楼，问问如果想把http、https端口换到80以外的其他端口，应该怎么操作
目前已经尝试：
- 防火墙开新端口
- 更改config.json
- 更改docker启动时的端口映射
